{% set name = "bokeh" %}
{% set version = "0.12.3" %}
{% set checksum = "e138941b62f59bc48bc5b8d249e90c03fed31c1d5abe47ab2ce9e4c83202f73c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: python setup.py install
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  build:
    - python

  run:
    - python
    - six >=1.5.2
    - requests >=1.2.3
    - pyyaml >=3.10
    - python-dateutil >=2.1
    - jinja2 >=2.7
    - numpy >=1.7.1
    - tornado >=4.3
    - futures >=3.0.3         # [py2k]
    - pandas
    - matplotlib

test:
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.charts
    - bokeh.charts.builders
    - bokeh.client
    - bokeh.command
    - bokeh.command.subcommands
    - bokeh.core
    - bokeh.core.compat
    - bokeh.core.compat.mplexporter
    - bokeh.core.compat.mplexporter.renderers
    - bokeh.core.validation
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.plotting
    - bokeh.sampledata
    - bokeh.server
    - bokeh.server.protocol
    - bokeh.server.protocol.messages
    - bokeh.server.views
    - bokeh.sphinxext
    - bokeh.themes
    - bokeh.util

  commands:
    - bokeh --help
    - bokeh-server --help

about:
  home: http://github.com/bokeh/bokeh
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Statistical and novel interactive HTML plots for Python

extra:
  recipe-maintainers:
    - almarklein
    - jakirkham
