{% set name = "bokeh" %}
{% set version = "0.12.6" %}
{% set checksum = "a2ddcc694c387440a2b361e741d2fa9a18ad0508a879a71f524a2f0ff7803181" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.5.2
    - requests >=1.2.3
    - pyyaml >=3.10
    - python-dateutil >=2.1
    - jinja2 >=2.7
    - numpy >=1.7.1
    - tornado >=4.3
    - futures >=3.0.3         # [py2k]
    - pandas
    - matplotlib
    - bkcharts >=0.2

test:
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.charts
    - bokeh.charts.builders
    - bokeh.client
    - bokeh.command
    - bokeh.command.subcommands
    - bokeh.core
    - bokeh.core.compat
    - bokeh.core.compat.mplexporter
    - bokeh.core.compat.mplexporter.renderers
    - bokeh.core.property
    - bokeh.core.validation
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.plotting
    - bokeh.sampledata
    - bokeh.server
    - bokeh.server.protocol
    - bokeh.server.protocol.messages
    - bokeh.server.views
    - bokeh.sphinxext
    - bokeh.themes
    - bokeh.util

  commands:
    - bokeh --help

about:
  home: http://github.com/bokeh/bokeh
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Statistical and novel interactive HTML plots for Python

extra:
  recipe-maintainers:
    - almarklein
    - jakirkham
    - ocefpaf
