{% set name = "bokeh" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bokeh-{{ version }}.tar.gz
  sha256: aa044829f66f08e9aeb74e33d538bc719270406124ea128bd7616e09e1561815

build:
  number: 0
  # Currently xyzservices >=2021.09.1 is not available on s390x
  skip: true  # [py<38 or s390x]
  script: 
    - {{ PYTHON }} -m pip install .
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  host:
    - python
    - colorama
    - pip
    - setuptools >=64
    - setuptools-git-versioning
    - wheel
  run:
    - python
    - jinja2 >=2.9
    - contourpy >=1
    - numpy >=1.11.3
    - packaging >=16.8
    - pandas >=1.2
    - pillow >=7.1.0
    - pyyaml >=3.10
    - tornado >=5.1
    - xyzservices >=2021.09.1

test:
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.client
    - bokeh.command
    - bokeh.command.subcommands
    - bokeh.core
    - bokeh.core.property
    - bokeh.core.validation
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.plotting
    - bokeh.sampledata
    - bokeh.server
    - bokeh.protocol
    - bokeh.protocol.messages
    - bokeh.server.views
    - bokeh.sphinxext
    - bokeh.themes
    - bokeh.util
  requires:
    - pip
  commands:
    - pip check || true   # [not win]
    - pip check || (exit 1)  # [win]
    - bokeh --help

about:
  home: https://bokeh.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  license_url: https://github.com/bokeh/bokeh/blob/main/LICENSE.txt
  summary: Bokeh is an interactive visualization library for modern web browsers. 
  description: |
    Bokeh is an interactive visualization library for modern web browsers. 
    It provides elegant, concise construction of versatile graphics, 
    and affords high-performance interactivity over large or streaming 
    datasets. Bokeh can help anyone who would like to quickly and easily 
    make interactive plots, dashboards, and data applications.
  doc_url: https://docs.bokeh.org
  doc_source_url: https://github.com/bokeh/bokeh/tree/main/docs/bokeh/source
  dev_url: https://github.com/bokeh/bokeh

extra:
  recipe-maintainers:
    - almarklein
    - jakirkham
    - mattpap
    - ocefpaf
    - philippjfr
