{% set name = "bokeh" %}
{% set version = "3.8.1" %}
{% set ignore_tests = " --ignore=gh/tests/unit/bokeh/models/test_plots.py" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bokeh-{{ version }}.tar.gz
    sha256: 40df8e632de367399d06979cbd76c9e68a133a3138e1adde37c4a4715ecb4d6e
  - url: https://github.com/bokeh/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: f26842f8f27c2527e7ce6bb41c16d259faee43b0b9f1f60348cd837ff5622c6f
    folder: gh

build:
  number: 1
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  host:
    - python
    - colorama
    - pip
    - setuptools >=77
    - setuptools-git-versioning
  run:
    - python
    - jinja2 >=2.9
    - contourpy >=1.2
    - narwhals >=1.13
    - numpy >=1.16
    - packaging >=16.8
    - pandas >=1.2
    - pillow >=7.1.0
    - pyyaml >=3.10
    - tornado >=6.2
    - xyzservices >=2021.09.1

# AttributeError: StamenTerrain
test:
  source_files:
    - gh/tests
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.application.handlers.code_runner
    - bokeh.application.handlers.handler
    - bokeh.client
    - bokeh.colors
    - bokeh.colors.color
    - bokeh.command.util
    - bokeh.core.enums
    - bokeh.core.properties
    - bokeh.core.property._sphinx
    - bokeh.core.property.descriptors
    - bokeh.core.property.singletons
    - bokeh.core.property.vectorization
    - bokeh.core.serialization
    - bokeh.core.templates
    - bokeh.core.types
    - bokeh.document
    - bokeh.embed
    - bokeh.embed.bundle
    - bokeh.embed.elements
    - bokeh.embed.server
    - bokeh.embed.util
    - bokeh.ext
    - bokeh.io.doc
    - bokeh.layouts
    - bokeh.model
    - bokeh.models
    - bokeh.palettes
    - bokeh.resources
    - bokeh.server.auth_provider
    - bokeh.server.callbacks
    - bokeh.server.tornado
    - bokeh.settings
    - bokeh.util.compiler
    - bokeh.util.dependencies
    - bokeh.util.info
    - bokeh.util.logconfig
    - bokeh.util.options
    - bokeh.util.serialization
    - bokeh.util.strings
    - bokeh.util.terminal
    - bokeh.util.token
    - bokeh.util.warnings
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Reducing the test scope due to failures and long runtime.
    - pytest {{ ignore_tests }} -v gh/tests/unit/bokeh/models/
    - bokeh --help
    - bokeh info

about:
  home: https://bokeh.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Bokeh is an interactive visualization library for modern web browsers.
  description: |
    Bokeh is an interactive visualization library for modern web browsers.
    It provides elegant, concise construction of versatile graphics,
    and affords high-performance interactivity over large or streaming
    datasets. Bokeh can help anyone who would like to quickly and easily
    make interactive plots, dashboards, and data applications.
  doc_url: https://docs.bokeh.org/en/latest
  dev_url: https://github.com/bokeh/bokeh

extra:
  recipe-maintainers:
    - almarklein
    - jakirkham
    - mattpap
    - ocefpaf
    - philippjfr
